name: run-groovy-application-on-schedule
run-name: スケジューラを使用した定期実行 ${{ github.actor }}
on:
  schedule:
    # TODO 動作確認後、停止
    - cron: '*/5 * * * *'
jobs:
  run-groovy-application:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'gradle'
      - run: chmod +x ./gradlew
      - run: ./gradlew run --no-daemon
