name: run-groovy-application
run-name: main branch is updated by ${{ github.actor }}
on: [push]
jobs:
  run-groovy-application:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'gradle'
      - run: chmod +x ./gradlew
      - run: ./gradlew run --no-daemon
